var manibronumber = prompt("Enter Mani bro's total expense for this month");
var umavaujunumber = prompt("Enter Uma Vauju's total expense for this month");
var baininumber = prompt("Enter Baini's total expense for this month");
var ashokbronumber = prompt("Enter Ashok bro's total expense for this month");
var otherbronumber = prompt("Enter Other bro's total expense for this month");
var sum = Number(manibronumber) + Number(umavaujunumber) + Number(baininumber) + Number(ashokbronumber) + Number(otherbronumber);
alert("Total expense for this month is: " + sum);
alert("Per head expencess for this month is: " + sum/5);
var Averageexpencess = sum/5;
var subtract1 = Number(manibronumber) - Number(Averageexpencess);
alert("Mani Bro owe/reveive to/from the group: " + subtract1);
var subtract2 = Number(umavaujunumber) - Number(Averageexpencess);
alert("Uma Vauju owe/reveive to/from the group: " + subtract2);
var subtract3 = Number(baininumber) - Number(Averageexpencess);
alert("Baini owe/reveive to/from the group: " + subtract3);
var subtract4 = Number(ashokbronumber) - Number(Averageexpencess);
alert("Ashok Bro owe/reveive to/from the group: " + subtract4);
var subtract5 = Number(otherbronumber) - Number(Averageexpencess);
alert("Other Bro owe/reveive to/from the group: " + subtract5);